version: '3.4'

services:
  todoapp:
    image: ${DOCKER_REGISTRY-}todoapp
    build:
      context: .
      dockerfile: ToDoApp/Dockerfile
    ports:
      - "5000:80"
      - "44388:443"

  todo.db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: ToDoAppDB
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"










